name: Playwright Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Change .env file
        run: cp .env.example .env
      - name: Run Playwright tests
        run: npx playwright test
        env:
          PASSWORD: ${{vars.PASSWORD}}
          API_KEY: ${{secrets.API_KEY}}
          NAME: ${{vars.NAME}}
          SURNAME: ${{vars.SURNAME}}
          TELE_NUMBER: ${{vars.TELE_NUMBER}}
          LOGIN: ${{secrets.LOGIN}}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
